// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-U9VaH4XaY4vTnPoNQVQOi11Ojq_btpM',
    appId: '1:840116567603:web:bf316241635af6b7baed46',
    messagingSenderId: '840116567603',
    projectId: 'khmapauth',
    authDomain: 'khmapauth.firebaseapp.com',
    storageBucket: 'khmapauth.firebasestorage.app',
    measurementId: 'G-VP6VLPX1NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRLs0ylLVQNTV1hT45DqkDnP2DoyjLbFg',
    appId: '1:840116567603:android:d8e51e10fd33bcdcbaed46',
    messagingSenderId: '840116567603',
    projectId: 'khmapauth',
    storageBucket: 'khmapauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQE7VP6TvJM3YuOWod6ezqTpHfFTBeik',
    appId: '1:840116567603:ios:1f581b1a425860a9baed46',
    messagingSenderId: '840116567603',
    projectId: 'khmapauth',
    storageBucket: 'khmapauth.firebasestorage.app',
    iosClientId: '840116567603-cmm4dig2ndb7cvv7o4plua88i0vjnsuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.khMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdQE7VP6TvJM3YuOWod6ezqTpHfFTBeik',
    appId: '1:840116567603:ios:1f581b1a425860a9baed46',
    messagingSenderId: '840116567603',
    projectId: 'khmapauth',
    storageBucket: 'khmapauth.firebasestorage.app',
    iosClientId: '840116567603-cmm4dig2ndb7cvv7o4plua88i0vjnsuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.khMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-U9VaH4XaY4vTnPoNQVQOi11Ojq_btpM',
    appId: '1:840116567603:web:25874b3f64016470baed46',
    messagingSenderId: '840116567603',
    projectId: 'khmapauth',
    authDomain: 'khmapauth.firebaseapp.com',
    storageBucket: 'khmapauth.firebasestorage.app',
    measurementId: 'G-M1PZPD16W0',
  );
}
